version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    container_name: postgres_user_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 1s
      timeout: 3s
      retries: 30
    env_file:
      - .env
